# Generated by Django 4.1.6 on 2023-02-22 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backpacker", "0003_remove_routemanager_routes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="dateTraveled",
        ),
        migrations.RemoveField(
            model_name="route",
            name="images",
        ),
        migrations.AddField(
            model_name="route",
            name="dateCreated",
            field=models.DateField(default=datetime.date(2023, 2, 22)),
        ),
        migrations.AddField(
            model_name="route",
            name="travelEnd",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 2, 22, 15, 17, 44, 733659, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="route",
            name="travelStart",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 2, 22, 15, 17, 50, 978, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
