# Generated by Django 4.1.6 on 2023-02-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backpacker", "0004_remove_route_datetraveled_remove_route_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="dateCreated",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="route",
            name="travelEnd",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="route",
            name="travelStart",
            field=models.TextField(),
        ),
    ]
