# Generated by Django 4.1.6 on 2023-02-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backpacker", "0005_alter_route_datecreated_alter_route_travelend_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="authorRating",
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
    ]
