# Generated by Django 4.1.6 on 2023-03-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpacker', '0006_route_authorrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='route',
            name='travelEnd',
        ),
        migrations.RemoveField(
            model_name='route',
            name='travelStart',
        ),
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='priceEstimate',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='tags',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='authorRating',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='dateCreated',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='routemanager',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
