# Generated by Django 4.1.6 on 2023-03-10 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backpacker", "0007_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routemanager",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="routemanager",
            name="likedRoutes",
            field=models.ManyToManyField(
                default=None, related_name="likedRoutes", to="backpacker.route"
            ),
        ),
        migrations.AlterField(
            model_name="routemanager",
            name="owner",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
