# Generated by Django 4.1.6 on 2023-03-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpacker', '0007_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routemanager',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
