# Generated by Django 4.1.6 on 2023-03-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backpacker", "0009_alter_review_route_userlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlike",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
