# Generated by Django 4.1.6 on 2023-03-14 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backpacker", "0010_alter_userlike_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlike",
            name="id",
        ),
        migrations.AlterField(
            model_name="userlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
