# Generated by Django 4.1.6 on 2023-03-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backpacker", "0008_alter_routemanager_id"),
        ("backpacker", "0013_userlike_id_alter_userlike_user_and_more"),
    ]

    operations = []
